<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function fin($limit)
    {
        return $this
            ->createQueryBuilder('n')
            ->select('n')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }


    public function findJoinedCategory(){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c, n FROM AppBundle:category c
                             JOIN c.news n' );
        try { return $query->getResult(); }
        catch (\Doctrine\ORM\NoResultException $e) {}

        }

    public function findOtherJoinedCategory($categoryId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c, n FROM AppBundle:category c
                             JOIN c.news n
                             WHERE c.id != :categoryId' )
        ->setParameter('categoryId', $categoryId)
        ->setMaxResults(5);
        try { return $query->getResult(); }
        catch (\Doctrine\ORM\NoResultException $e) {}

    }



}
