<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Notice;

/**
 * NoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends EntityRepository
{
	public function findAllOrderedById() {
		return $this->getEntityManager()
		->createQuery( 'SELECT n FROM AppBundle:News n
				 ORDER BY n.id DESC' ) 
		->getResult();
	}
	
	public function findRescentNotice($limit) {
		return $this
		 ->createQueryBuilder('e')
            ->select('e')
            ->where('e.PublishedAt <= :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('e.PublishedAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
			->getResult();
	}
	public function moreNotice($limit){

		return $this
			->createQueryBuilder('e')
			->select('e')
			->where('e.PublishedAt <= :now')
			->setParameter('now', new \DateTime())
			->orderBy('e.PublishedAt', 'DESC')
			->setMaxResults($limit)
			->getQuery()
			->getResult();

	}
}
