<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Testimony;

/**
 * TestimonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonyRepository extends EntityRepository
{
	public function findAllOrderedById() {
		return $this->getEntityManager()
		->createQuery( 'SELECT n FROM AppBundle:News n
				 ORDER BY n.id DESC' ) 
		->getResult();
	}
	
	public function findRescentTestimonies($limit) {
		return $this
		 ->createQueryBuilder('e')
            ->select('e')
            ->where('e.PublishedAt <= :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('e.PublishedAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
			->getResult();
	}

	public function moreTestimony($id,$limit) {
		return $this
			->createQueryBuilder('e')
			->select('e')
			->where('e.id != :id')
			->setParameter('id', $id)
			->orderBy('e.id', 'DESC')
			->setMaxResults($limit)
			->getQuery()
			->getResult();
	}
}
